// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBkpjBshYQFFQRKxlU3mrKBYhTOO1wbxs',
    appId: '1:912228473522:web:9d7ef55eadf06eb2bb87ab',
    messagingSenderId: '912228473522',
    projectId: 'chat-app-cc05e',
    authDomain: 'chat-app-cc05e.firebaseapp.com',
    storageBucket: 'chat-app-cc05e.firebasestorage.app',
    measurementId: 'G-FS9CPG2F8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBCyqBxjKRm86ldoDqdlfZg8b7ET9p2o',
    appId: '1:912228473522:android:828eb65da1d0c8d3bb87ab',
    messagingSenderId: '912228473522',
    projectId: 'chat-app-cc05e',
    storageBucket: 'chat-app-cc05e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3WKwB2ZcA9Yf4lP2PyKRq4j_nlGS_HrQ',
    appId: '1:912228473522:ios:ec14a59599f12370bb87ab',
    messagingSenderId: '912228473522',
    projectId: 'chat-app-cc05e',
    storageBucket: 'chat-app-cc05e.firebasestorage.app',
    iosBundleId: 'com.example.chartApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3WKwB2ZcA9Yf4lP2PyKRq4j_nlGS_HrQ',
    appId: '1:912228473522:ios:ec14a59599f12370bb87ab',
    messagingSenderId: '912228473522',
    projectId: 'chat-app-cc05e',
    storageBucket: 'chat-app-cc05e.firebasestorage.app',
    iosBundleId: 'com.example.chartApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBkpjBshYQFFQRKxlU3mrKBYhTOO1wbxs',
    appId: '1:912228473522:web:ad99e8970f82df63bb87ab',
    messagingSenderId: '912228473522',
    projectId: 'chat-app-cc05e',
    authDomain: 'chat-app-cc05e.firebaseapp.com',
    storageBucket: 'chat-app-cc05e.firebasestorage.app',
    measurementId: 'G-XYSCDEJWPD',
  );
}
